ERROR - 2024-08-27 03:00:20 --> Error connecting to the database: Error: Class "SQLite3" not found in C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:89
Stack trace:
#0 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\SQLite3\Connection->connect(false)
#1 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php(59): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(74): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(54): ExampleDatabaseTest->loadDependencies()
#4 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php(248): ExampleDatabaseTest->setUpDatabase()
#5 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestCase.php(1207): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#7 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestCase.php(964): PHPUnit\Framework\TestResult->run(Object(ExampleDatabaseTest))
#8 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#9 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(651): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#13 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#14 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\phpunit(107): PHPUnit\TextUI\Command::main()
#15 C:\xampp\htdocs\dw\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#16 {main}
ERROR - 2024-08-27 03:00:20 --> Error connecting to the database: Error: Class "SQLite3" not found in C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:89
Stack trace:
#0 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\SQLite3\Connection->connect(false)
#1 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php(59): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(74): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(54): ExampleDatabaseTest->loadDependencies()
#4 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php(248): ExampleDatabaseTest->setUpDatabase()
#5 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestCase.php(1207): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#7 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestCase.php(964): PHPUnit\Framework\TestResult->run(Object(ExampleDatabaseTest))
#8 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#9 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(651): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#13 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#14 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\phpunit(107): PHPUnit\TextUI\Command::main()
#15 C:\xampp\htdocs\dw\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#16 {main}
ERROR - 2024-08-27 03:01:30 --> Error connecting to the database: Error: Class "SQLite3" not found in C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:89
Stack trace:
#0 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\SQLite3\Connection->connect(false)
#1 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php(59): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(74): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(54): ExampleDatabaseTest->loadDependencies()
#4 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php(248): ExampleDatabaseTest->setUpDatabase()
#5 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestCase.php(1207): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#7 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestCase.php(964): PHPUnit\Framework\TestResult->run(Object(ExampleDatabaseTest))
#8 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#9 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(651): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#13 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#14 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\phpunit(107): PHPUnit\TextUI\Command::main()
#15 C:\xampp\htdocs\dw\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#16 {main}
ERROR - 2024-08-27 03:01:30 --> Error connecting to the database: Error: Class "SQLite3" not found in C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:89
Stack trace:
#0 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\SQLite3\Connection->connect(false)
#1 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php(59): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(74): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(54): ExampleDatabaseTest->loadDependencies()
#4 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php(248): ExampleDatabaseTest->setUpDatabase()
#5 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestCase.php(1207): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#7 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestCase.php(964): PHPUnit\Framework\TestResult->run(Object(ExampleDatabaseTest))
#8 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#9 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(651): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#13 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#14 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\phpunit(107): PHPUnit\TextUI\Command::main()
#15 C:\xampp\htdocs\dw\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#16 {main}
ERROR - 2024-08-27 03:01:58 --> Error connecting to the database: Error: Class "SQLite3" not found in C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:89
Stack trace:
#0 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\SQLite3\Connection->connect(false)
#1 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php(59): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(74): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(54): ExampleDatabaseTest->loadDependencies()
#4 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php(248): ExampleDatabaseTest->setUpDatabase()
#5 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestCase.php(1207): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#7 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestCase.php(964): PHPUnit\Framework\TestResult->run(Object(ExampleDatabaseTest))
#8 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#9 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(651): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#13 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#14 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\phpunit(107): PHPUnit\TextUI\Command::main()
#15 C:\xampp\htdocs\dw\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#16 {main}
ERROR - 2024-08-27 03:01:58 --> Error connecting to the database: Error: Class "SQLite3" not found in C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:89
Stack trace:
#0 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\SQLite3\Connection->connect(false)
#1 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php(59): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(74): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(54): ExampleDatabaseTest->loadDependencies()
#4 C:\xampp\htdocs\dw\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php(248): ExampleDatabaseTest->setUpDatabase()
#5 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestCase.php(1207): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#7 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestCase.php(964): PHPUnit\Framework\TestResult->run(Object(ExampleDatabaseTest))
#8 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#9 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\Framework\TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(651): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#13 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\src\TextUI\Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#14 C:\xampp\htdocs\dw\vendor\phpunit\phpunit\phpunit(107): PHPUnit\TextUI\Command::main()
#15 C:\xampp\htdocs\dw\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2024-08-27 05:04:36 --> Call to a member function getStatusCode() on null
in ROOTPATH\spark on line 100.

CRITICAL - 2024-08-27 05:05:20 --> Call to a member function getStatusCode() on null
in ROOTPATH\spark on line 100.

CRITICAL - 2024-08-27 05:05:27 --> Call to a member function getStatusCode() on null
in ROOTPATH\spark on line 100.

CRITICAL - 2024-08-27 05:05:42 --> Call to a member function getStatusCode() on null
in ROOTPATH\spark on line 100.

CRITICAL - 2024-08-27 05:06:40 --> Call to a member function getStatusCode() on null
in ROOTPATH\spark on line 100.

CRITICAL - 2024-08-27 06:29:02 --> Class "App\Libraries\Prediction" not found
in APPPATH\Controllers\Home.php on line 44.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2024-08-27 06:29:04 --> Class "App\Libraries\Prediction" not found
in APPPATH\Controllers\Home.php on line 44.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2024-08-27 06:29:07 --> Class "App\Libraries\Prediction" not found
in APPPATH\Controllers\Home.php on line 44.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
